backend:
  name: git-gateway
  branch: main
media_folder: 'src/assets/images'
public_folder: '/assets/images'
site_url: https://recipes.ehrensberger.org
editor:
  preview: false
collections:
  - name: 'recipes'
    label: 'Recipes'
    label_singular: 'Recipe'
    folder: 'src/recipes'
    slug: '{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Quote', name: 'quote', widget: 'string', required: false }
      - {
          label: 'Category',
          name: 'tags',
          widget: 'select',
          options:
            ['breakfast', 'salad', 'soup', 'starter', 'main dish', 'bread', 'dessert', 'cookies'],
        }
      - { label: 'Language', name: 'language', widget: 'select', options: ['en', 'de', 'fr', 'it'] }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Yield', name: 'yield', widget: 'string', required: false }
      - { label: 'Prep', name: 'prep', widget: 'string', required: false }
      - { label: 'Cook', name: 'cook', widget: 'string', required: false }
      - { label: 'Source', name: 'source', widget: 'string', required: false }
      - { label: 'Ingredients', name: 'ingredients', widget: 'text' }
      - { label: 'Instructions', name: 'body', widget: 'markdown' }

  - label: 'Globals'
    name: 'globals'
    files:
      - label: 'Site Data'
        name: 'site_data'
        delete: false
        file: 'src/_data/site.json'
        fields:
          - { label: 'site_name', name: 'site_name', widget: 'string' }
          - { label: 'title', name: 'title', widget: 'string' }
          - { label: 'description', name: 'description', widget: 'string' }
          - { label: 'url', name: 'url', widget: 'string' }
          - { label: 'locale', name: 'locale', widget: 'string' }
          - { label: 'author', name: 'author', widget: 'string' }
